name: MultiWorld
version: '1.2'
main: fr.rudy.multiworld.MultiWorldPlugin
api-version: '1.21'
depend: [DataBaseAPI]

commands:
  spawn:
    description: Téléporte au spawn global
    usage: /spawn

  setspawn:
    description: Définit le spawn global à ta position
    usage: /setspawn
    permission: multiworld.admin

  world:
    description: Commande de gestion des mondes
    usage: /world <create|remove|tp|setspawn>
    permission: multiworld.admin.world